- ddb/feature/git/actions.py
- ddb/feature/shell/integrations.py
- ddb/feature/smartcd/__init__.py
- ddb/feature/smartcd/actions.py
- ddb/utils/file.py
- tests/feature/git/test_fix_files_permissions.py
- tests/feature/shell/test_actions.py
- tests/feature/smartcd/test_smartcd.py
> Adding windows support for shims generation, environment variable update and some kind of smartcd

- ddb/binary/binary.py
- ddb/feature/docker/actions.py
- ddb/feature/docker/binaries.py
- tests/feature/run/test_run.py
It was not re-generating the binary
> Correction of a bug when updating binary options conditions

- CHANGELOG.md
- ddb/feature/smartcd/__init__.py
- ddb/feature/smartcd/actions.py
- ddb/feature/smartcd/schema.py
- docs/10-default_configuration.md
- docs/11-project_configuration/03-Dockerfile.md
- tests/feature/smartcd/test_smartcd.data/aliases/ddb.yml
- tests/feature/smartcd/test_smartcd.py
> Adding the aliases configuration on Smartcd

- ddb/feature/docker/schema.py
- ddb/feature/jsonnet/lib/ddb.docker.libjsonnet
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_traefik/ddb.prod.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_traefik/docker-compose.expected.ci.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_traefik/docker-compose.expected.prod.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_traefik/docker-compose.yml.jsonnet
Fix #25, see detail in the ticket
> Adding certresolver configuration in ddb configuration

- ddb/feature/jsonnet/lib/ddb.docker.libjsonnet
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_traefik/docker-compose.expected.prod.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_traefik/docker-compose.yml.jsonnet
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_variables/ddb.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_variables/docker-compose.expected.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_variables/docker-compose.yml.jsonnet
- tests/feature/jsonnet/test_jsonnet.py
It will still listen for http request but redirect to https
> Jsonnet : addition of force_https parameter to VirtualHost (Fix #43)

- CHANGELOG.md
- ddb/feature/shell/integrations.py
> fix(shell): Fix binary shims when -h/--help is given as argument

- CHANGELOG.md
- ddb/feature/fixuid/actions.py
- tests/feature/fixuid/test_fixuid.data/from-scratch-empty/docker/Dockerfile.expected
- tests/it/test_watch.data/watch-fixuid/expected/Dockerfile
- tests/it/test_watch.data/watch-fixuid/files/.docker/db/Dockerfile.jinja
- tests/it/test_watch.data/watch-fixuid/files/.docker/db/fixuid.yml
- tests/it/test_watch.data/watch-fixuid/files/docker-compose.yml.jsonnet
- tests/it/test_watch.py
This also brings some integration tests to check fixuid configuration is properly generated in watch mode
> fix(fixuid): Enhance fixuid configuration when image has no entrypoint

- docs/faq.md
Hey,
Here is my small documentation contribution to this cool tool !
> Update faq with tips for docker feature

- CHANGELOG.md
- ddb/binary/binary.py
- ddb/feature/docker/binaries.py
- ddb/feature/run/actions.py
- ddb/utils/docker.py
- tests/feature/run/test_run.data/exe/docker-compose.yml
- tests/feature/run/test_run.py
- tests/it/test_binaries.data/docker1_exe/docker-compose.yml
- tests/utils/test_docker_utils.data/docker-compose.yml
- tests/utils/test_docker_utils.py
Check if the container is up if user run "ddb run <binary>" on a command flagged "exe". 
If it is down, it will be launch.
Fix #105
> evol(Docker Binary): Check if the container is up for exe binaries

- .gitignore
- ddb/feature/jsonnet/lib/ddb.docker.libjsonnet
- docs/features/jsonnet.md
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_variables/ddb.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_variables/docker-compose.expected.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_variables/docker-compose.yml.jsonnet
> evol(jsonnet): add JoinObjectArray method

- ddb/feature/copy/actions.py
- tests/feature/copy/test_copy.data/copy-no-dispatch/ca-certificates/some-cert.crt
- tests/feature/copy/test_copy.data/copy-no-dispatch/ddb.yml
- tests/feature/copy/test_copy.py
Correction du NoneType error si le dispatch n'est pas défini ou à None
> fix(copy): Correction du NoneType error

- CHANGELOG.md
- ddb/__main__.py
- ddb/config/config.py
- ddb/config/merger.py
- ddb/feature/bootstrap.py
- ddb/feature/core/__init__.py
- ddb/feature/feature.py
- docs/configuration.md
- tests/conftest.py
- tests/feature/symlinks/test_symlinks.py
- tests/it/test_config_it.data/deep-local-custom-strategy/ddb.local.yml
- tests/it/test_config_it.data/deep-local-custom-strategy/ddb.yml
- tests/it/test_config_it.data/merge-default/ddb.yml
- tests/it/test_config_it.data/merge-insert-strategy/ddb.yml
- tests/it/test_config_it.data/merge-insert-strategy2/ddb.yml
- tests/it/test_config_it.data/merge-insert-strategy3/ddb.yml
- tests/it/test_config_it.py
- tests/utilstest.py
This also enhance the configuration bootstrap to make possible to merge from default configuration lying in Marshmallow default values.
Close #121
> feat(configuration): Add insert/insert_if_missing merge strategies.

- ddb/feature/core/actions.py
- ddb/feature/docker/actions.py
- ddb/utils/table_display.py
- tests/feature/docker/test_docker.py
> fix(update): fix can only concatenate str (not "list") to str (#143)

- ddb/feature/shell/actions.py
- ddb/feature/shell/integrations.py
> fix(bash): exclude PWD environment variable from backup/restore (#142)

- ddb/feature/jsonnet/lib/ddb.docker.libjsonnet
- docs/features/jsonnet.md
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_expose/docker-compose.expected.yml
- tests/feature/jsonnet/test_jsonnet.data/docker_compose_expose/docker-compose.yml.jsonnet
- tests/feature/jsonnet/test_jsonnet.py
This new function help to expose service ports using docker.port_prefix
> feat(jsonnet): add Expose function in ddb.docker.libjsonnet

- ddb/feature/permissions/actions.py
- tests/feature/permissions/test_permissions.data/inherit_from_template/script.jinja.sh
- tests/feature/permissions/test_permissions.py
if not in permissions.specs 
fix #147
> feat(permission): copy permission from template file to target

- docs/features/jsonnet.md
> Update Xdebug documentation

- ddb/command/command.py
- ddb/config/config.py
- ddb/feature/core/__init__.py
- tests/feature/traefik/test_traefik.py
- tests/it/test_traefik_it.py
- tests/test_main.py
> feat(configure): ensure project configuration file is available before configure (#170)

- ddb/feature/shell/__init__.py
- ddb/feature/shell/schema.py
> fix(shell): add support for relative paths in shell.path.directory (#168)

- ddb/feature/shell/integrations.py
> fix(shell): Use `_` instead of `-` to sanitize environment variable name (#160)

- ddb/binary/binary.py
- ddb/cache/shelve_cache.py
- ddb/config/config.py
- ddb/config/migrations.py
- ddb/event/events.py
- ddb/feature/docker/__init__.py
- ddb/feature/docker/actions.py
- ddb/feature/docker/binaries.py
- ddb/feature/docker/schema.py
- ddb/feature/docker/utils.py
- ddb/feature/jsonnet/__init__.py
- ddb/feature/jsonnet/lib/ddb.docker.libjsonnet
- ddb/feature/jsonnet/schema.py
- ddb/feature/shell/actions.py
- ddb/feature/shell/integrations.py
- docs/features/docker.md
- docs/features/jsonnet.md
- tests/feature/docker/test_docker.py
- tests/feature/run/test_run.py
> Global binaries

- ddb/config/config.py
- ddb/feature/core/__init__.py
- ddb/feature/core/actions.py
- ddb/feature/docker/binaries.py
- ddb/feature/jsonnet/actions.py
- docs/commands.md
- tests/it/test_config_it.py
> feat(config): enhance config command output and add options (#189)

- ddb/feature/core/actions.py
- ddb/feature/shell/__init__.py
- ddb/feature/shell/actions.py
- ddb/feature/shell/integrations.py
- docs/commands.md
> fix(binary): fix orphan containers when using global binaries (#195)

- .github/workflows/ci.yml
- ddb/feature/cookiecutter/actions.py
- ddb/feature/docker/binaries.py
- ddb/feature/shell/integrations.py
- ddb/utils/table_display.py
- pylintrc
- setup.py
> fix(shell): Replaced tempfile with mktemp to remove the deprecation warning

- ddb/feature/docker/binaries.py
> feat: Always specify the docker-compose.yml file in docker run

- ddb/config/config.py
- ddb/feature/core/__init__.py
- ddb/feature/core/schema.py
- ddb/feature/docker/__init__.py
- ddb/feature/jsonnet/lib/ddb.docker.libjsonnet
- docs/configuration.md
- docs/faq.md
- docs/features/core.md
- tests/config/test_config.data/load/expect.yml
- tests/config/test_config.data/load/expect_env.yml
- tests/config/test_config.data/load/home/ddb.yaml
- tests/config/test_config.data/load/project/ddb.yml
- tests/config/test_config.data/load/user_home/ddb.local.yml
- tests/config/test_config.data/load/user_home/ddb.yml
- tests/config/test_config.py
- tests/feature/shell/test_actions.py
- tests/utilstest.py
> feat(config): Allow loading ddb(.local).yml from user home.

- ddb/feature/core/actions.py
- docs/faq.md
- tests/it/test_core_it.py
> feat(core): Create ddb.old on self-update
